name: etron_flutter
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  country_picker: ^2.0.21
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  dropdown_search: ^6.0.2
  file_picker: ^10.2.4
  http: ^1.5.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  url_launcher: ^6.3.2 
  path_provider: ^2.1.5
  open_filex: ^4.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo-name.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/logo-name.png
    - .env.development
    - .env
    - .env.pre
    - .env.stg


  generate: true
